### PR TITLE
Validate address

### LINKED ISSUE #3: Valid address API endpoint
Implement [GET] /api/addresses/{address}/validity per the Lykke specs

Should check and return address validity.

Should check and return wallet address validity

Response:

```js
{
 // Flag, which indicates that the address is valid
“isValid”: boolean
}
```

### PR DESCRIPTION
**Pull request by stdevOzkar**
validate address using `pyskycoin` lib. refs #3 close #3

### CODE REVIEW

**Comment by olemis** [comment]
@stdevOzkar @codeshard wasn't this already imnplemented by Ratmil ?

**Comment by stdevOzkar** [comment]
Yes, it was done by Ratmil. Just now I saw his branch, Perhaps was a misunderstood between us. There are slight differences but is almost the same solution. May I close & delete this PR?
May his branch could be merged in `develop` and avoid future mistakes?

**Comment by olemis** [comment]
@stdevOzkar His branch has not been merged with develop (yet) because PySkycoin installation from requirements.txt is not working as expected . He's fixinfg that now .

Please use asignee field in issues to claim an issue before start working on it .

**Comment by olemis** [comment]
@olemis I understood what happened here . It's my fault , sorry

**Comment by olemis** [comment]
@olemis jftr , issue = https://github.com/skycoin/pyskycoin/issues/54

**Comment by olemis** [comment]
let's better do this in #105

**Pull request closed without merging**
